### ISSUE TITLE
希望增加计分板和boosbar功能

### ISSUE THREAD

**Issue by IceBlues** [MikkoAyaka/WolfHunter#3]
如题，愿意提交pr实现。

**Comment by MikkoAyaka** [comment]
### Bossbar 动态进度条
**可复用：**[Bossbars.kt](https://github.com/MikkoAyaka/WolfHunter/blob/dev/src/main/kotlin/cn/wolfmc/minecraft/wolfhunter/presentation/bossbar/Bossbars.kt)
**实现于：**[UHCRunningStage.kt](https://github.com/MikkoAyaka/WolfHunter/blob/dev/src/main/kotlin/cn/wolfmc/minecraft/wolfhunter/application/uhc/UHCRunningStage.kt)
**详细需求：** UHC模式的游戏流程是线性时间轴，具体时间轴安排如下：
- 第0秒：开始游戏，给予开局保护
- 第30秒：开局保护结束
- 第130秒：开始收缩边界，将在300秒内收缩到50格
- 第520秒：进一步收缩，在90秒内收缩到10格大小
- 第610秒：世界开始塌陷
- 第730秒：流程结束
现阶段的游戏流程主要依赖文字公告通知玩家，玩家反馈不够直观，希望能够以动态 bossbar 的形式看到当前的游戏进展，预知下一个阶段会发生的事件，并提前做出准备。
### 计分板
**可复用：**[scoreboard-library](https://github.com/MegavexNetwork/scoreboard-library)
**实现于：** presentation.scoreboard(自行创建包和相关文件)
**接入于：**[UHCGameService](https://github.com/MikkoAyaka/WolfHunter/blob/dev/src/main/kotlin/cn/wolfmc/minecraft/wolfhunter/application/uhc/UHCGameService.kt)
**详细需求：** 计分板展示的内容模板大概如下：
- 剩余队伍：7支
- 当前队伍：红队(剩余3人)
- 世界中心：↗
剩余队伍可以从 GameInstance 中获取全部队伍，并过滤掉玩家数量为0的队伍
当前队伍要根据 Player 实例 前往 GameInstance 获取
世界中心的实现比较复杂，需要计算玩家坐标的 yaw 判断玩家当前看向的方向，与玩家当前坐标到 0,0 坐标方向的夹角，计算出最终的方向符号，可以参考 infrastructure.mechanism.BowAiming 中的 autoAiming 算法

**Comment by MikkoAyaka** [comment]
已实现

**Comment by MikkoAyaka** [comment]
已实现
